# Generated by Django 2.2.5 on 2019-11-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('avatar', models.CharField(max_length=100, null=True)),
                ('settings', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
