# Generated by Django 2.2.5 on 2019-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_lable',
            new_name='chat_label',
        ),
        migrations.AddField(
            model_name='member',
            name='last_unseen',
            field=models.IntegerField(null=True),
        ),
    ]
