# Generated by Django 2.2.5 on 2019-11-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20191121_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
