# Generated by Django 3.0.5 on 2020-04-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20191128_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dialog',
        ),
    ]
